// <auto-generated />
using System;
using BillEase360_CodeFirstApproach.Invoice.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BillEase360_CodeFirstApproach.Invoice.Infrastructure.Migrations
{
    [DbContext(typeof(InvoiceDbContext))]
    partial class InvoiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BillEase360_CodeFirstApproach.Invoice.Domain.Entities.InvoiceGSTDetails", b =>
                {
                    b.Property<Guid>("GSTDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("GSTType")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<Guid>("InvoiceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true);

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("Rate")
                        .HasColumnType("DECIMAL(4,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("DECIMAL(12,2)");

                    b.HasKey("GSTDetailID");

                    b.HasIndex("InvoiceID");

                    b.ToTable("InvoiceGSTDetails", (string)null);
                });

            modelBuilder.Entity("BillEase360_CodeFirstApproach.Invoice.Domain.Entities.InvoiceLineItems", b =>
                {
                    b.Property<Guid>("LineItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("Discount")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<decimal>("GSTRate")
                        .HasColumnType("DECIMAL(4,2)");

                    b.Property<Guid>("InvoiceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true);

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<decimal>("TaxableValue")
                        .HasColumnType("DECIMAL(12,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("DECIMAL(10,2)");

                    b.HasKey("LineItemID");

                    b.ToTable("InvoiceLineItems", (string)null);
                });

            modelBuilder.Entity("BillEase360_CodeFirstApproach.Invoice.Domain.Entities.Invoices", b =>
                {
                    b.Property<Guid>("InvoiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("VARCHAR(60)");

                    b.Property<string>("InvoiceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(20)")
                        .HasDefaultValue("Pending");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true);

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(20)")
                        .HasDefaultValue("Sales");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(20)")
                        .HasDefaultValue("Draft");

                    b.Property<decimal>("TaxableAmount")
                        .HasColumnType("DECIMAL(12,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("DECIMAL(12,2)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InvoiceID");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_Invoices_InvoiceNumber");

                    b.ToTable("Invoices", (string)null);
                });

            modelBuilder.Entity("BillEase360_CodeFirstApproach.Invoice.Domain.Entities.InvoiceGSTDetails", b =>
                {
                    b.HasOne("BillEase360_CodeFirstApproach.Invoice.Domain.Entities.Invoices", "Invoices")
                        .WithMany()
                        .HasForeignKey("InvoiceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
